#!/bin/bash
#PBS -P ad73
#PBS -q normal
#PBS -l walltime=48:00:00,jobfs=400GB
#PBS -l software=cp2k
#PBS -l mem=380GB
#PBS -l ncpus=96
#PBS -l wd
#PBS -j oe
#PBS -l storage=scratch/ad73+gdata/ad73+scratch/ep0


JOBNAME="test"
OUT_NAME="test"

export CP2K_DATA_DIR="/home/561/hm1876/cp2k/data"

cd $PBS_O_WORKDIR

module purge
module load pbs

HFX_check=`grep "&HF" ${JOBNAME}.inp | grep -v "#"`
if [ $HFX_check ] ; then 
	sed -i "/@SET LT_STORAGE_LOCATION/d" ${JOBNAME}.inp
	sed -i "1i "@SET\ LT_STORAGE_LOCATION\ $PBS_JOBFS"" ${JOBNAME}.inp
	sed -i "/\<STORAGE_LOCATION\>/d" ${JOBNAME}.inp
	sed -i "/\<MAX_DISK_SPACE\>/d" ${JOBNAME}.inp
	sed -i "/EPS_STORAGE_SCALING/a\STORAGE_LOCATION \$LT_STORAGE_LOCATION" ${JOBNAME}.inp
	sed -i "/EPS_STORAGE_SCALING/a\MAX_DISK_SPACE 8000" ${JOBNAME}.inp
fi

source ~/CP2K_JOB_PARAMETERS

### Intel-mpi ###
module load intel-mpi/2021.4.0
mpirun /g/data/ad73/cp2k/cp2k-2023.1-intelmpi/cp2k.psmp -i ${JOBNAME}.inp -o ${OUT_NAME}.out
# mpirun /g/data/ad73/cp2k/cp2k-2024.1-intelmpi/cp2k.psmp -i ${JOBNAME}.inp -o ${OUT_NAME}.out

### Open-mpi ###
# module load cp2k/2023.1
# export CP2K_DATA_DIR="/home/561/hm1876/cp2k/data"
## Single node
# mpirun cp2k.psmp -o ${OUT_NAME}.out -i ${JOBNAME}.inp
## Multiple nodes 
# mpirun -mca coll_hcoll_enable 0 cp2k.psmp -o ${OUT_NAME}.out -i ${JOBNAME}.inp
# mpirun cp2k.psmp -o ${OUT_NAME}.out -i ${JOBNAME}.inp


### OpenMP -intelmpi ##
# module load intel-mpi/2021.4.0
# export I_MPI_DEBUG=5
# export OMP_NUM_THREADS=2
# export PPN=$( grep -c $HOSTNAME $PBS_NODEFILE )
# uniq < $PBS_NODEFILE > hosts.txt
# mpirun -np $(( $PBS_NCPUS / $OMP_NUM_THREADS )) -ppn $(( $PPN / $OMP_NUM_THREADS )) -f hosts.txt /g/data/ad73/cp2k/cp2k-9.1-intelmpi/cp2k.psmp -o ${OUT_NAME}.out -i ${JOBNAME}.inp

### OpenMP -openmpi ##
# export OMP_NUM_THREADS=2
# mpirun -np $(( $PBS_NCPUS / $OMP_NUM_THREADS )) --map-by node:PE=$OMP_NUM_THREADS --rank-by core --report-bindings /g/data/ad73/cp2k/cp2k-9.1/cp2k.psmp -o ${OUT_NAME}.out -i ${JOBNAME}.inp

